---
name: pd-forked-task
description: |
  Context Forking 데모 스킬.
  격리된 서브에이전트 컨텍스트에서 실행됩니다.
user-invocable: true
context: fork
agent: general-purpose
model: sonnet
allowed-tools:
  - Read
  - Write
  - Edit
  - Grep
  - Glob
  - Bash
version: "1.0.0"
---

# Forked Task Executor

> **Pattern:** S3 - Skill Context Forking
> **Mode:** `context: fork` → Isolated subagent execution

---

## Execution Context

This skill runs in a **forked context**:
- Isolated from main conversation
- Has its own tool permissions
- Does not pollute main agent context
- Results returned as L1 summary

---

## Instructions

Execute the task specified in $ARGUMENTS:

1. **Understand** the task requirements
2. **Plan** the implementation approach
3. **Execute** using available tools
4. **Report** results in L1 format:

```yaml
taskId: {generated-id}
agentType: general-purpose
summary: "What was accomplished"
status: success | partial | failed

priority: HIGH
l2Path: .agent/outputs/general-purpose/{taskId}.md
nextActionHint: "Recommended follow-up"
```

---

## Isolation Benefits

| Aspect | Main Context | Forked Context |
|--------|--------------|----------------|
| Tool Access | Full | Restricted by allowed-tools |
| Context Pollution | Risk | None |
| Token Usage | Shared | Isolated |
| Resume | N/A | Via agent_id |

---

*Generated by /build "Progressive-Disclosure" | Level 50*
