
# [ODA-Governed HWP Automation Script]
# Auto-generated by Orion V3 HWP Pipeline
# Protocol: Mathpix -> PowerShell -> HWPX
[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$dllPath = "C:\HwpAuth\Security.dll"
$desktop = [Environment]::GetFolderPath("Desktop")
$filePath = Join-Path $desktop "oda_compliant_output.hwpx"

Start-Sleep -Seconds 1
Get-Process -Name "Hwp", "HwpAutomation" -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1

Write-Host "[ODA] Launching HWP (2-Column)..." -ForegroundColor Cyan

$regPath = "HKCU:\Software\HNC\HwpAutomation\Modules"
if (-not (Test-Path $regPath)) { New-Item -Path $regPath -Force | Out-Null }
Set-ItemProperty -Path $regPath -Name "FilePathCheckerModule" -Value $dllPath

Start-Job -ScriptBlock {
    Start-Sleep -Milliseconds 2000
    $wshell = New-Object -ComObject WScript.Shell
    $wshell.SendKeys("{ENTER}")
} | Out-Null

$hwp = New-Object -ComObject "HWPFrame.HwpObject"
$hwp.XHwpWindows.Item(0).Visible = $true
$hwp.RegisterModule("FilePathCheckDLL", "FilePathCheckerModule")
$hwp.Clear(1)

# [Style Configuration]
$act = $hwp.CreateAction("CharShape")
$set = $act.CreateSet()
$act.GetDefault($set)
$set.SetItem("Height", 1000)
$act.Execute($set)

function Insert-Text($t) {
    if (-not $t) { return }
    $act = $hwp.CreateAction("InsertText")
    $set = $act.CreateSet()
    $act.GetDefault($set)
    $set.SetItem("Text", $t)
    $act.Execute($set)
}

function Insert-Equation($s) {
    if (-not $s) { return }
    $act = $hwp.CreateAction("EquationCreate")
    $set = $act.CreateSet()
    $act.GetDefault($set)
    $set.SetItem("String", $s)
    $set.SetItem("BaseUnit", 130)
    $act.Execute($set)
}

function New-Line {
    $hwp.Run("BreakPara")
}

# --- Document Actions ---
New-Line
New-Line
Insert-Text '4. '
Insert-Equation 'x^{2}+x-1=0'
Insert-Text '일 때, 다음 식의 값을 구하시오. '
New-Line
Insert-Text '(1) '
Insert-Equation '(x+2)(x-1)(x+4)(x-3)+5'
New-Line
Insert-Equation '16'
New-Line
Insert-Text '(2) '
Insert-Equation 'x^{5}-5 x'
New-Line
Insert-Equation '-3'
New-Line
New-Line
New-Line
Insert-Text '5. 다음을 만족시키는 '
Insert-Equation 'n'
Insert-Text '의 값을 구하시오. '
New-Line
Insert-Equation '(2^{2}+1)(2^{4}+1)(2^{8}+1)(2^{16}+1)(2^{32}+1)= over {1}{3}(2^{n}-1)'
New-Line
New-Line
New-Line
Insert-Text '6. 다음 다항식의 전개식에서 모든 계수의 합을 구하시 오. '
New-Line
Insert-Equation 'begin{array}{l} 1+(1+x)+(1+x+x^{2})^{2}+(1+x+x^{2}+x^{3})^{3}  +(1+x+x^{2}+x^{3}+x^{4})^{4} end{array}'
New-Line
New-Line
New-Line
$hwp.Run("BreakColumn")
Insert-Text '7. 다항식 '
Insert-Equation '(1+x+x^{2})^{2}(1+x)+(1-x+x^{2}+x^{3})^{3}'
Insert-Text '의 전개식에서 일차항의 계수를 구하시오. '
New-Line
Insert-Equation '0'
New-Line
New-Line
New-Line
Insert-Text '8. '
Insert-Equation 'a+b=4, a b=2'
Insert-Text '일 때, 다음 식의 값을 구하시오. (단, '
Insert-Equation 'a  >= q b'
Insert-Text ') '
New-Line
Insert-Text '(1) '
Insert-Equation 'a-b'
New-Line
Insert-Equation 'begin{array}{|l|} hline 2  sqrt {2}  hline end{array}'
New-Line
Insert-Text '(2) '
Insert-Equation 'a^{2}-b^{2}'
New-Line
Insert-Equation '8  sqrt {2}'
New-Line
Insert-Text '(3) '
Insert-Equation 'a^{3}-b^{3}'
New-Line
Insert-Equation '28  sqrt {2}'
New-Line
New-Line
New-Line
Insert-Text '9. '
Insert-Equation 'x+y=1, x^{3}+y^{3}=19'
Insert-Text '일 때, 다음 식의 값을 구하 시오. '
New-Line
Insert-Text '(1) '
Insert-Equation 'x y'
New-Line
Insert-Equation '-6'
New-Line
Insert-Text '(2) '
Insert-Equation 'x^{2}+y^{2}'
New-Line
Insert-Equation 'begin{array}{|l|} hline 13  hline end{array}'
New-Line
Insert-Text '(3) '
Insert-Equation 'x^{4}+y^{4}'
Insert-Text '□ '
New-Line
Insert-Text '97 '
New-Line
Insert-Text '(4) '
Insert-Equation 'x^{5}+y^{5}'
Insert-Text '211 '
New-Line
Insert-Text '8 '
New-Line
New-Line
New-Line
Insert-Text '1. 다항식의 연산 '
# --- End Document Actions ---

# [ODA Strategy: Dynamic Column Control Function]
# Defines a robust function to switch column layouts dynamically.
# Tries API first (Clean), falls back to SendKeys (Dirty) if API fails.

function Set-Column {
    param([int]$Count)
    
    Write-Host "[ODA] Attempting to set Column Count to: $Count"
    
    try {
        $act = $hwp.CreateAction("MultiColumn")
        $set = $act.CreateSet()
        $act.GetDefault($set)
        
        $set.SetItem("Count", $Count)
        $set.SetItem("Type", 0)       # Normal
        $set.SetItem("SameSize", 1)   # Equal Width
        $set.SetItem("SameGap", 2835) # 10mm
        
        if ($act.Execute($set)) {
            Write-Host "[ODA] Success: API applied $Count columns." -ForegroundColor Green
            return
        }
    } catch {
        Write-Host "[ODA] Warning: API threw exception. $_" -ForegroundColor Yellow
    }
    
    Write-Host "[ODA] Fallback: Using SendKeys macro..." -ForegroundColor Yellow
    $wshell = New-Object -ComObject WScript.Shell
    
    # Alt+W, U (Legacy) or Alt+J, D (New) - stick to Legacy as it worked
    $wshell.SendKeys("%(w)u")
    Start-Sleep -Seconds 2
    
    if ($Count -eq 1) {
        $wshell.SendKeys("1") 
    } elseif ($Count -eq 2) {
        $wshell.SendKeys("2")
    }
    
    Start-Sleep -Milliseconds 500
    $wshell.SendKeys("{ENTER}")
    Write-Host "[ODA] Applied via Macro."
}

# Apply Requested Layout
Set-Column -Count 2

$hwp.SaveAs($filePath, "HWPX", "")
Write-Host "[ODA] Saved: $filePath" -ForegroundColor Green
