#!/bin/bash
# Progressive-Disclosure PreToolUse Hook (H1)
# Pattern: Intercept Task calls, inject L1/L2 format instructions
# Matcher: Task
# Generated by: /build "Progressive-Disclosure" | Level 50

set -e

# Parse input from Claude Code
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
SUBAGENT_TYPE=$(echo "$INPUT" | jq -r '.tool_input.subagent_type // empty')

# Skip for conversational agents
SKIP_AGENTS=("prompt-assistant" "onboarding-guide" "statusline-setup" "claude-code-guide")
for agent in "${SKIP_AGENTS[@]}"; do
    if [[ "$SUBAGENT_TYPE" == "$agent" ]]; then
        echo '{}'
        exit 0
    fi
done

# Only process Task tool calls
if [[ "$TOOL_NAME" != "Task" ]]; then
    echo '{}'
    exit 0
fi

# L1/L2/L3 Format Instructions
L1_FORMAT_INSTRUCTIONS=$(cat <<'EOF'
## OUTPUT FORMAT REQUIREMENT (L1/L2/L3 Progressive Disclosure)

You MUST structure your response in L1/L2/L3 format:

### L1 Summary (Return to Main Agent - MAX 500 tokens)
```yaml
taskId: {8-char unique id}
agentType: {your agent type}
summary: "1-2 sentence summary"
status: success | partial | failed

priority: CRITICAL | HIGH | MEDIUM | LOW
recommendedRead:
  - anchor: "#section-name"
    reason: "why read this"

l2Index:
  - anchor: "#section-name"
    tokens: {estimated}
    priority: CRITICAL | HIGH | MEDIUM | LOW
    description: "section contents"

l2Path: .agent/outputs/{agentType}/{taskId}.md
requiresL2Read: true | false
nextActionHint: "suggested next step"
```

### L3 Detail (Save to file)
Save detailed findings to the l2Path file with `## Section {#anchor}` format.
EOF
)

# Return hook output with additionalContext injection
cat <<EOF
{
  "hookSpecificOutput": {
    "additionalContext": $(echo "$L1_FORMAT_INSTRUCTIONS" | jq -Rs .),
    "updatedInput": {
      "run_in_background": true
    }
  }
}
EOF
