# generated by datamodel-codegen:
#   filename:  event.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class EventType(Enum):
    """
    Type of the event.
    """

    ACTION_START = 'ACTION_START'
    ACTION_END = 'ACTION_END'
    ERROR = 'ERROR'
    STATE_CHANGE = 'STATE_CHANGE'
    THOUGHT = 'THOUGHT'


class Event(BaseModel):
    """
    Represents a discrete event within a Trace.
    """

    trace_id: str = Field(..., description='ID of the Trace this event belongs to.')
    timestamp: str = Field(..., description='ISO 8601 timestamp.')
    event_type: EventType = Field(..., description='Type of the event.')
    component: str = Field(
        ...,
        description="Component that generated the event (e.g., 'ReasoningEngine', 'ActionRegistry').",
    )
    details: Optional[Dict[str, Any]] = Field(
        None,
        description='Structured details (e.g., action name, arguments, error message).',
    )
