# generated by datamodel-codegen:
#   filename:  master.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from . import action as action_1
from . import event as event_1
from . import job as job_1
from . import metric as metric_1
from . import plan as plan_1
from . import trace as trace_1


class OrionMasterOntology(BaseModel):
    """
    Aggregates all system schemas for code generation
    """

    plan: Optional[plan_1.Schema] = None
    job: Optional[job_1.Schema] = None
    trace: Optional[trace_1.Schema] = None
    action: Optional[action_1.Schema] = None
    event: Optional[event_1.Schema] = None
    metric: Optional[metric_1.Schema] = None
