# generated by datamodel-codegen:
#   filename:  master.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Schema(BaseModel):
    """
    Represents an executable capability (Tool) in the Orion System.
    """

    name: str = Field(..., description="Unique name of the action (e.g., 'read_file')")
    description: Optional[str] = Field(
        None, description='Human-readable description of what this action does.'
    )
    parameters: Dict[str, Any] = Field(
        ..., description='JSON Schema defining the expected arguments for this action.'
    )
    required_permissions: Optional[List[str]] = Field(
        None, description='List of security scopes required to execute this action.'
    )
