# generated by datamodel-codegen:
#   filename:  master.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Schema(BaseModel):
    """
    Represents quantitative performance data.
    """

    trace_id: Optional[str] = Field(None, description='ID of the Trace context.')
    name: str = Field(
        ...,
        description="Name of the metric (e.g., 'execution_time_ms', 'tokens_used').",
    )
    value: float = Field(..., description='Numeric value of the metric.')
    unit: Optional[str] = Field(
        None, description="Unit of measurement (e.g., 'ms', 'count')."
    )
    timestamp: str = Field(..., description='ISO 8601 timestamp.')
