# generated by datamodel-codegen:
#   filename:  master.json

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

from . import job


class Schema(BaseModel):
    id: str = Field(..., description='Unique Plan UUID')
    type: Optional[str] = Field('Plan', description='Type discriminator')
    created_at: Optional[datetime] = None
    meta_version: Optional[int] = Field(1, description='Metadata version')
    plan_id: str = Field(..., description='User-facing Plan ID')
    objective: str = Field(..., description='High-level objective')
    ontology_impact: Optional[List[str]] = Field(
        [], description='Impacted Ontology Concepts'
    )
    jobs: List[job.Schema] = Field(..., description='List of executable jobs')
