# generated by datamodel-codegen:
#   filename:  master.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    """
    Current status of the trace.
    """

    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class Schema(BaseModel):
    """
    Represents a logical execution flow (Chain of Thought).
    """

    task_id: str = Field(..., description='ID of the Task this trace belongs to.')
    start_time: str = Field(..., description='ISO 8601 timestamp.')
    end_time: Optional[str] = Field(None, description='ISO 8601 timestamp.')
    status: Status = Field(..., description='Current status of the trace.')
    tags: Optional[List[str]] = Field(
        None, description="Tags for filtering (e.g., 'refactor', 'bugfix')."
    )
