# generated by datamodel-codegen:
#   filename:  plan.schema.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Job(BaseModel):
    id: str = Field(..., description='Unique Job ID')
    action_name: str = Field(..., description='Name of the action to execute')
    action_args: Optional[Dict[str, Any]] = Field(
        {}, description='Arguments for the action'
    )
    description: Optional[str] = Field(None, description='Description of the job')
    input_context: Optional[List[str]] = Field([], description='Context files/dirs')
    evidence: Optional[str] = Field(None, description='Reasoning/Evidence for this job')
    role: Optional[str] = Field(None, description='Role responsible for this job')
