"""
Math Image Parsing Pipeline - Alignment Module (Stage D)

Implements text-visual alignment:
- TextVisualMatcher for matching elements
- ConsistencyChecker for validating matches
- InconsistencyDetector for finding mismatches
- AlignmentEngine for orchestrating the process
"""

from .matcher import (
    MatcherConfig,
    SpatialMatcher,
    SemanticMatcher,
    TextVisualMatcher,
)
from .consistency import (
    ConsistencyConfig,
    EquationGraphConsistency,
    CoordinateConsistency,
    LabelConsistency,
    ConsistencyChecker,
)
from .inconsistency import (
    InconsistencyConfig,
    LabelInconsistencyDetector,
    EquationInconsistencyDetector,
    CoordinateInconsistencyDetector,
    InconsistencyDetector,
)
from .engine import (
    AlignmentEngineConfig,
    AlignmentEngine,
    create_alignment_engine,
    align_text_and_vision,
)
from .semantic_matcher import (
    MatchStrategy,
    MatchResult,
    SemanticMatchPair,
    SemanticMatcherConfig,
    LabelTokenizer,
    MatchTypeInferrer,
    SpatialMatcher as SemanticSpatialMatcher,
    SemanticMatcher as AlignmentLayerMatcher,
    create_semantic_matcher,
    match_elements,
    extract_visual_refs_from_merged,
)
from .validator import (
    ValidationRuleCode,
    ValidatorSeverity,
    ValidationMode,
    VisionSpecValidationIssue,
    VisionSpecValidationResult,
    VisionSpecValidatorConfig,
    VisionSpecValidator,
    create_validator,
    validate_vision_spec,
    validate_for_alignment,
)
from .latex_aligner import (
    AlignmentRule,
    LaTeXAlignerConfig,
    AlignmentCandidate,
    LaTeXAlignmentResult,
    LaTeXParser,
    VariableLabelRule,
    CoefficientCoordinateRule,
    FunctionCurveTypeRule,
    LaTeXAligner,
)
from .reconstruction_controller import (
    ReconstructionAction,
    ReviewValidationType,
    ModificationRequest,
    ReviewResult,
    MathReviewReport,
    ReconstructionResult,
    ReconstructionConfig,
    MathReviewInterface,
    ReconstructionController,
    create_reconstruction_controller,
)
from .hitl_controller import (
    HITLMode,
    HITLTrigger,
    QuestionType,
    HITLControllerConfig,
    HITLQuestion,
    HITLResponse,
    HITLSession,
    TriggerEvaluator,
    LowConfidenceEvaluator,
    MatchAmbiguityEvaluator,
    ValidationWarningEvaluator,
    ReconstructionTriggerEvaluator,
    HITLQuestionGenerator,
    HITLController,
    create_hitl_controller,
    create_snapshot_controller,
)
from .output_formatter import (
    OutputFormat,
    DetailLevel,
    OutputFormatterConfig,
    FormattedOutput,
    BatchExportResult,
    L1SummaryFormatter,
    L2DetailedFormatter,
    L3FullFormatter,
    MarkdownFormatter,
    OutputFormatter,
    create_output_formatter,
    format_alignment_result,
)
from .orchestrator import (
    OrchestratorPhase,
    OrchestratorStatus,
    OrchestratorConfig,
    PhaseResult,
    OrchestratorResult,
    ValidationPhaseHandler,
    MatchingPhaseHandler,
    AlignmentPhaseHandler,
    HITLPhaseHandler,
    OutputPhaseHandler,
    AlignmentOrchestrator,
    create_orchestrator,
    run_alignment_workflow,
)

__all__ = [
    # Matcher
    "MatcherConfig",
    "SpatialMatcher",
    "SemanticMatcher",
    "TextVisualMatcher",
    # Consistency
    "ConsistencyConfig",
    "EquationGraphConsistency",
    "CoordinateConsistency",
    "LabelConsistency",
    "ConsistencyChecker",
    # Inconsistency
    "InconsistencyConfig",
    "LabelInconsistencyDetector",
    "EquationInconsistencyDetector",
    "CoordinateInconsistencyDetector",
    "InconsistencyDetector",
    # Engine
    "AlignmentEngineConfig",
    "AlignmentEngine",
    "create_alignment_engine",
    "align_text_and_vision",
    # Validator
    "ValidationRuleCode",
    "ValidatorSeverity",
    "ValidationMode",
    "VisionSpecValidationIssue",
    "VisionSpecValidationResult",
    "VisionSpecValidatorConfig",
    "VisionSpecValidator",
    "create_validator",
    "validate_vision_spec",
    "validate_for_alignment",
    # Semantic Matcher (AlignmentLayer)
    "MatchStrategy",
    "MatchResult",
    "SemanticMatchPair",
    "SemanticMatcherConfig",
    "LabelTokenizer",
    "MatchTypeInferrer",
    "SemanticSpatialMatcher",
    "AlignmentLayerMatcher",
    "create_semantic_matcher",
    "match_elements",
    "extract_visual_refs_from_merged",
    # LaTeX Aligner
    "AlignmentRule",
    "LaTeXAlignerConfig",
    "AlignmentCandidate",
    "LaTeXAlignmentResult",
    "LaTeXParser",
    "VariableLabelRule",
    "CoefficientCoordinateRule",
    "FunctionCurveTypeRule",
    "LaTeXAligner",
    # Reconstruction Controller
    "ReconstructionAction",
    "ReviewValidationType",
    "ModificationRequest",
    "ReviewResult",
    "MathReviewReport",
    "ReconstructionResult",
    "ReconstructionConfig",
    "MathReviewInterface",
    "ReconstructionController",
    "create_reconstruction_controller",
    # HITL Controller
    "HITLMode",
    "HITLTrigger",
    "QuestionType",
    "HITLControllerConfig",
    "HITLQuestion",
    "HITLResponse",
    "HITLSession",
    "TriggerEvaluator",
    "LowConfidenceEvaluator",
    "MatchAmbiguityEvaluator",
    "ValidationWarningEvaluator",
    "ReconstructionTriggerEvaluator",
    "HITLQuestionGenerator",
    "HITLController",
    "create_hitl_controller",
    "create_snapshot_controller",
    # Output Formatter
    "OutputFormat",
    "DetailLevel",
    "OutputFormatterConfig",
    "FormattedOutput",
    "BatchExportResult",
    "L1SummaryFormatter",
    "L2DetailedFormatter",
    "L3FullFormatter",
    "MarkdownFormatter",
    "OutputFormatter",
    "create_output_formatter",
    "format_alignment_result",
    # Orchestrator
    "OrchestratorPhase",
    "OrchestratorStatus",
    "OrchestratorConfig",
    "PhaseResult",
    "OrchestratorResult",
    "ValidationPhaseHandler",
    "MatchingPhaseHandler",
    "AlignmentPhaseHandler",
    "HITLPhaseHandler",
    "OutputPhaseHandler",
    "AlignmentOrchestrator",
    "create_orchestrator",
    "run_alignment_workflow",
]
