# 🤖 AUTO-GENERATED BY scripts/codegen.py
# DO NOT EDIT MANUALLY

from typing import List, Optional, Dict, Any
from enum import Enum
from pydantic import BaseModel

class RoleEnum(str, Enum):
    MASTER = 'Master'
    WORKER = 'Worker'
    AUDITOR = 'Auditor'
    RESEARCHER = 'Researcher'
    ARCHITECT = 'Architect'
    QA = 'QA'
    FORGE = 'Forge'
    CIPHER = 'Cipher'
    AURA = 'Aura'

class Job(BaseModel):
    id: str
    role: RoleEnum
    description: str
    input_context: Optional[List[str]] = None
    evidence: str

class Plan(BaseModel):
    plan_id: str
    objective: str
    ontology_impact: List[str]
    jobs: List[Job]

class Properties(BaseModel):
    pass

class Ontology(BaseModel):
    apiName: str
    description: Optional[str] = None
    primaryKey: str
    properties: Properties

class Idiomatic_pattern(BaseModel):
    pattern: Optional[str] = None
    usage: Optional[str] = None
    philosophy: Optional[str] = None

class Language(BaseModel):
    language_id: str
    name: str
    philosophy_summary: Optional[str] = None
    idiomatic_patterns: Optional[List[Idiomatic_pattern]] = None

class Concept(BaseModel):
    concept_id: str
    name: str
    category: str
    prerequisites: Optional[List[str]] = None
    related_concepts: Optional[List[str]] = None

class Source(BaseModel):
    pass

class Implementation(BaseModel):
    impl_id: str
    concept_id: str
    language_id: str
    syntax_template: str
    design_rationale: str
    sources: Optional[List[Source]] = None
