# 🤖 AUTO-GENERATED BY scripts/codegen.py
# DO NOT EDIT MANUALLY
# This file serves as the 'Digital Twin' of the Ontology.

from typing import List, Optional, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime

class OrionObject(BaseModel):
    """Base schema for all Ontology Objects in the Orion System. Enforces Palantir-style identification and typing."""
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    id: str = Field(..., description="Unique Primary Key (UUID or immutable slug). Maps to OSDK $primaryKey.")
    type: str = Field(..., description="The Object Type Name. Maps to OSDK $apiName.")
    created_at: str = Field(..., description="ISO 8601 Timestamp of creation.")
    updated_at: Optional[str] = Field(None, description='ISO 8601 Timestamp of last modification.')
    provenance: Optional[str] = Field(None, description='ID of the Agent or Task that created this object (Lineage).')
    _version: int = Field(..., description="Optimistic Concurrency Control Version. Increment on every write.")
    _locked_by: Optional[str] = Field(None, description='Session ID holding a lock on this object. Null if unlocked.')

class Plan(OrionObject):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    plan_id: str = Field(...)
    objective: str = Field(...)
    ontology_impact: List[str] = Field(..., description="List of Ontology Objects affected (e.g., Employee, Ticket)")
    jobs: List[Dict[str, Any]] = Field(...)

class Ontology(OrionObject):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    apiName: str = Field(..., description="The unique API name of the object type (e.g., Employee)")
    description: Optional[str] = Field(None, description='')
    primaryKey: str = Field(..., description="The property ID acting as the primary key")
    properties: Dict[str, Any] = Field(...)
