#!/bin/bash
# Progressive-Disclosure PostToolUse Hook (H2)
# Pattern: Process Task results, extract L1 metadata, provide guidance
# Matcher: Task
# Generated by: /build "Progressive-Disclosure" | Level 50

set -e

# Parse input from Claude Code
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
TOOL_RESULT=$(echo "$INPUT" | jq -r '.tool_result // empty')
AGENT_ID=$(echo "$INPUT" | jq -r '.tool_result.agent_id // empty')

# Only process Task tool results
if [[ "$TOOL_NAME" != "Task" ]]; then
    echo '{}'
    exit 0
fi

# Log agent ID for resume support (P7 pattern)
LOG_DIR="${CLAUDE_WORKSPACE:-.}/.agent/logs"
mkdir -p "$LOG_DIR"
if [[ -n "$AGENT_ID" ]]; then
    echo "$(date -Iseconds) | AgentID: $AGENT_ID | Tool: $TOOL_NAME" >> "$LOG_DIR/agent_ids.log"
fi

# Extract priority from result (if L1 format was followed)
PRIORITY=$(echo "$TOOL_RESULT" | grep -oP 'priority:\s*\K(CRITICAL|HIGH|MEDIUM|LOW)' | head -1 || echo "MEDIUM")
L2_PATH=$(echo "$TOOL_RESULT" | grep -oP 'l2Path:\s*\K[^\s]+' | head -1 || echo "")

# Generate reading guidance based on priority
case "$PRIORITY" in
    "CRITICAL")
        GUIDANCE="MUST read recommendedRead L3 sections immediately"
        ;;
    "HIGH")
        GUIDANCE="SHOULD read recommendedRead L3 sections"
        ;;
    "MEDIUM")
        GUIDANCE="MAY read L3 sections on demand"
        ;;
    "LOW")
        GUIDANCE="L1 summary is sufficient, skip L3"
        ;;
    *)
        GUIDANCE="Review L1 summary and decide if L3 reading needed"
        ;;
esac

# Return hook output with guidance
cat <<EOF
{
  "hookSpecificOutput": {
    "guidance": "$GUIDANCE",
    "agentId": "$AGENT_ID",
    "l2Path": "$L2_PATH",
    "priority": "$PRIORITY"
  }
}
EOF
